# Generated by Django 6.0.7 on 2026-07-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('percentage', models.FloatField()),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
