# Generated by Django 6.0.7 on 2026-08-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeverse', '0002_topic_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='topic',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
