# Generated by Django 6.0.7 on 2026-08-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeverse', '0004_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='not_to_do',
            field=models.TextField(default=''),
        ),
    ]
