# Generated by Django 6.0.7 on 2026-08-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeverse', '0006_progress_created_at_progress_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='code_example',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='topic',
            name='key_topics',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='topic',
            name='why_it_matters',
            field=models.TextField(blank=True, default=''),
        ),
    ]
